# experiment_0:
#   name: "gravity_long_epoch_regularized"
#   data_params:
#     n_train: 100
#     n_val: 20
#     force_fn: "gravity"
#   train_params:
#     gnn_hp:
#       hidden: 256
#       msg_dim: 32
#     gkan_hp:
#       hidden_layers: 1
#       hidden: 8
#       node_hidden_layers: 1
#       node_hidden: 8
#       msg_dim: 4
#       grid_size: 5
#       lamb_l1: 1.0
#       lamb_entropy: 2.0
#     training_hp:
#       epochs: 50
#       batch_size: 16
#       kan_batch_size: 16
#       lr: 1e-3
#       lamb: 0.1
#   visualization_params:
#     save_video: True
#     plot_splines: True

# experiment_0_a:
#   name: "gravity_long_epoch"
#   data_params:
#     n_train: 100
#     n_val: 20
#     force_fn: "gravity"
#   train_params:
#     gnn_hp:
#       hidden: 256
#       msg_dim: 32
#     gkan_hp:
#       hidden_layers: 1
#       hidden: 8
#       node_hidden_layers: 1
#       node_hidden: 8
#       msg_dim: 4
#       grid_size: 5
#       lamb_l1: 0
#       lamb_entropy: 0
#     training_hp:
#       epochs: 50
#       batch_size: 16
#       kan_batch_size: 16
#       lr: 1e-3
#       lamb: 0
#   visualization_params:
#     save_video: True
#     plot_splines: True

# experiment_0b:
#   name: "gravity_long_epoch_regularized_minimal"
#   data_params:
#     n_train: 100
#     n_val: 20
#     force_fn: "gravity"
#   train_params:
#     gnn_hp:
#       hidden: 256
#       msg_dim: 32
#     gkan_hp:
#       hidden_layers: 2
#       hidden: 4
#       node_hidden_layers: 2
#       node_hidden: 4
#       msg_dim: 2
#       grid_size: 5
#       lamb_l1: 1.0
#       lamb_entropy: 2.0
#     training_hp:
#       epochs: 50
#       batch_size: 16
#       kan_batch_size: 16
#       lr: 1e-3
#       lamb: 0.15
#   visualization_params:
#     save_video: True
#     plot_splines: True

# experiment_0b:
#   name: "gravity_extra_long_epoch_regularized_minimal"
#   data_params:
#     n_train: 150
#     n_val: 20
#     force_fn: "gravity"
#   train_params:
#     gnn_hp:
#       hidden: 256
#       msg_dim: 32
#     gkan_hp:
#       hidden_layers: 2
#       hidden: 4
#       node_hidden_layers: 2
#       node_hidden: 4
#       msg_dim: 2
#       grid_size: 5
#       lamb_l1: 1.0
#       lamb_entropy: 2.0
#     training_hp:
#       epochs: 200
#       batch_size: 16
#       kan_batch_size: 16
#       lr: 1e-3
#       lamb: 0.15
#   visualization_params:
#     save_video: True
#     plot_splines: True

# experiment_0c:
#   name: "gravity_small"
#   data_params:
#     n_train: 150
#     n_val: 20
#     force_fn: "gravity"
#   train_params:
#     gnn_hp:
#       hidden: 256
#       msg_dim: 32
#     gkan_hp:
#       hidden_layers: 2
#       hidden: 4
#       node_hidden_layers: 0
#       node_hidden: 4
#       msg_dim: 2
#       grid_size: 5
#       lamb_l1: 1.0
#       lamb_entropy: 2.0
#     training_hp:
#       epochs: 100
#       batch_size: 32
#       kan_batch_size: 32
#       lr: 1e-3
#       lamb: 0.2
#   visualization_params:
#     save_video: True
#     plot_splines: True

# test:
#   name: "test"
#   data_params:
#     n_train: 50
#     n_val: 20
#     force_fn: "gravity"
#   train_params:
#     gnn_hp:
#       hidden: 256
#       msg_dim: 32
#     gkan_hp:
#       hidden_layers: 2
#       hidden: 4
#       node_hidden_layers: 0
#       node_hidden: 4
#       msg_dim: 2
#       grid_size: 5
#       lamb_l1: 1.0
#       lamb_entropy: 2.0
#     training_hp:
#       epochs: 1
#       batch_size: 32
#       kan_batch_size: 32
#       lr: 1e-3
#       lamb: 0.2
#   visualization_params:
#     save_video: True
#     plot_splines: True

experiment_1a:
  name: "gravity_small_medium"
  data_params:
    n_train: 200
    n_val: 20
    force_fn: "gravity"
  train_params:
    gnn_hp:
      hidden: 256
      msg_dim: 32
    gkan_hp:
      hidden_layers: 4
      hidden: 4
      node_hidden_layers: 0
      node_hidden: 4
      msg_dim: 2
      grid_size: 5
      lamb_l1: 0.5
      lamb_entropy: 1.0
      adam_warmup_epochs: 0
      grid_update_freq: 15 # might be important for interpretability but might cause instability, turn off for now.
      grid_update_warmup: 5
      max_grid_updates: 2
    training_hp:
      epochs: 67
      batch_size: 32
      kan_batch_size: 32768
      lr: 1e-3
      lamb: 0.0
  visualization_params:
    save_video: True
    plot_splines: True

experiment_1b:
  name: "linear_gravity_small_medium"
  data_params:
    n_train: 200
    n_val: 20
    force_fn: "linear_gravity"
  train_params:
    gnn_hp:
      hidden: 256
      msg_dim: 32
    gkan_hp:
      hidden_layers: 4
      hidden: 4
      node_hidden_layers: 0
      node_hidden: 4
      msg_dim: 2
      grid_size: 5
      lamb_l1: 0.5
      lamb_entropy: 1.0
      adam_warmup_epochs: 21
      grid_update_freq: 15
      grid_update_warmup: 25
      max_grid_updates: 2
    training_hp:
      epochs: 67
      batch_size: 32
      kan_batch_size: 32768
      lr: 1e-3
      lamb: 0.0
  visualization_params:
    save_video: True
    plot_splines: True

experiment_1c:
  name: "cubic_gravity_small_medium"
  data_params:
    n_train: 200
    n_val: 20
    force_fn: "cubic_gravity"
  train_params:
    gnn_hp:
      hidden: 256
      msg_dim: 32
    gkan_hp:
      hidden_layers: 4
      hidden: 4
      node_hidden_layers: 0
      node_hidden: 4
      msg_dim: 2
      grid_size: 5
      lamb_l1: 0.5
      lamb_entropy: 1.0
      adam_warmup_epochs: 21
      grid_update_freq: 15
      grid_update_warmup: 25
      max_grid_updates: 2
    training_hp:
      epochs: 67
      batch_size: 32
      kan_batch_size: 32768
      lr: 1e-3
      lamb: 0.0
  visualization_params:
    save_video: True
    plot_splines: True
